### ISSUE TITLE
state report is with a typo in French (this is confusing)

### ISSUE THREAD

**Issue by jluc2808** [Deejayfool/hass-shutter-card#94] opened 2023-05-01 22:00 UTC
hello , 

The state report for cover in french is now :  'était ouvert' 
There is a typo, the syntax should be :  'état ouvert' (without the i) 

this is not a big problem, but the report is confusing, because 'était' (in french) means 'was' and not 'state' 
so person not aware of this mistake, ask me, if the old state 'was' open, what is the state now  ...

**Comment by Deejayfool** [comment] 2023-05-02 07:09
Duplicate of #35

**Closed by Deejayfool** 2023-05-02 07:09 UTC
