### ISSUE TITLE
french translation of "state" is wrong

### ISSUE THREAD

**Issue by jluc2808** [Deejayfool/hass-shutter-card#110] opened 2024-01-03 09:08 UTC
now the state translation in french is "était",  should be "état" 

this mistake is enoying because the state shown "était ouvert" means "was opened", with this wrong label people think that this info is the right one and confuse a lot, because they are waiting for the state now and not the state before. 

could you just change the translation. 

I think it's not a very big change but it's a very big consequence.

many thanks

**Comment by Deejayfool** [comment] 2024-01-03 09:34
Duplicate of #104

**Closed by Deejayfool** 2024-01-03 09:34 UTC
Labels: duplicate

**Comment by jluc2808** [comment] 2024-01-03 12:16
sorry but i don't understand is it still wrong or is it upadated with the right message ?
